# Generated by Django 4.2.4 on 2023-08-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='suequipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
