# Generated by Django 4.2.4 on 2023-08-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0002_jugador_suequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='suequipo',
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='troneo.equipo')),
                ('equipo_visitante', models.ForeignKey(limit_choices_to={'equipo_local': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='troneo.equipo')}, on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='troneo.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troneo.equipo')),
            ],
        ),
    ]
