# Generated by Django 4.2.4 on 2023-08-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0004_relacion_entre_jugadores_y_equipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='goles_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_perdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
