# Generated by Django 4.2.4 on 2023-08-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0005_equipo_goles_contra_equipo_goles_favor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='troneo.equipo'),
        ),
    ]
