# Generated by Django 4.2.4 on 2023-08-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0007_alter_partido_equipo_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='troneo.equipo'),
        ),
    ]
