# Generated by Django 4.2.4 on 2023-08-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0008_alter_partido_equipo_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(limit_choices_to={'nombre__contains': 'local'}, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='troneo.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(limit_choices_to={'nombre__contains': 'visitante'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='troneo.equipo'),
        ),
    ]
