# Generated by Django 4.2.4 on 2023-08-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troneo', '0009_alter_partido_equipo_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='troneo.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(limit_choices_to={'id__ne': models.F('equipo_local')}, on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='troneo.equipo'),
        ),
    ]
